

export const rows = [
    {
        id: 1,
        Name: "Jon Snow",
        Email: "jonsnow@gmail.com",
        Age: 35,
        Phone: "(665)121-5454",
        Access: "Admin",
    },
    {
        id: 2,
        Name: "Cersei Lannister",
        Email: "cerseilannister@gmail.com",
        Age: 42,
        Phone: "(421)314-2288",
        Access: "Admin",
    },
    {
        id: 3,
        Name: "Jaime Lannister",
        Email: "jaimelannister@gmail.com",
        Age: 45,
        Phone: "(422)982-6739",
        Access: "Admin",
    },
    {
        id: 4,
        Name: "Anya Stark",
        Email: "anyastark@gmail.com",
        Age: 16,
        Phone: "(921)425-6742",
        Access: "Manager",
    },
    {
        id: 5,
        Name: "Daenerys Targaryen",
        Email: "daenerystargaryen@gmail.com",
        Age: 31,
        Phone: "(421)445-1189",
        Access: "Manager",
    },
    {
        id: 6,
        Name: "Ever Melisandre",
        Email: "evermelisandre@gmail.com",
        Age: 150,
        Phone: "(232)545-6483",
        Access: "User",
    },
    {
        id: 7,
        Name: "Ferrara Clifford",
        Email: "ferraraclifford@gmail.com",
        Age: 44,
        Phone: "(543)124-0123",
        Access: "User",
    },
    {
        id: 8,
        Name: "Rossini Frances",
        Email: "rossinifrances@gmail.com",
        Age: 36,
        Phone: "(222)444-5555",
        Access: "User",
    },
    {
        id: 9,
        Name: "Harvey Roxie",
        Email: "harveyroxie@gmail.com",
        Age: 65,
        Phone: "(444)555-6239",
        Access: "User",
    },
];

